services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--configFile=/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
    networks:
      - web

  landing:
    image: garoverr/primo-landing:dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=Host(`primo-data.fr`)"
      - "traefik.http.routers.landing.entrypoints=websecure"
      - "traefik.http.routers.landing.tls.certresolver=myresolver"
      - "traefik.http.services.landing.loadbalancer.server.port=80"
    networks:
      - web

  frontend:
    image: garoverr/primo-frontend:dev
    environment:
      VITE_API_URL: "https://api.primo-data.fr"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.primo-data.fr`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    driver: bridge
