name: Back Build Test

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    uses: ./.github/workflows/common-test.yml
    with:
      working-directory: back
      run-command: "yarn run build"
      cache-lock-path: back/yarn.lock
