name: Front Build Test

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    uses: ./.github/workflows/common-test.yml
    with:
      working-directory: web
      run-command: "mkdir -p web && touch web/env-config.js && yarn --cwd web run build"
      cache-lock-path: web/yarn.lock
