name: Front Build & Start Test

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    uses: ./.github/workflows/common-test.yml
    with:
      working-directory: web
      run-command: |
        yarn build
        yarn preview --port 4173 &
        sleep 5
      cache-lock-path: web/yarn.lock
