name: Front Build Test

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build:
    uses: ./.github/workflows/common-test.yml
    with:
      working-directory: web
      run-command: "touch web/env-config.js"
      run-command: "yarn run build"
      cache-lock-path: web/yarn.lock
